// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"database/sql/driver"
	"encoding/json"
	"fmt"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type MovementType string

const (
	MovementTypeOPENINGSTOCK MovementType = "OPENING_STOCK"
	MovementTypePURCHASE     MovementType = "PURCHASE"
	MovementTypeSALE         MovementType = "SALE"
	MovementTypeRETURN       MovementType = "RETURN"
	MovementTypeDAMAGE       MovementType = "DAMAGE"
	MovementTypeLOSS         MovementType = "LOSS"
	MovementTypeADJUSTMENT   MovementType = "ADJUSTMENT"
	MovementTypeEXPIRY       MovementType = "EXPIRY"
)

func (e *MovementType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MovementType(s)
	case string:
		*e = MovementType(s)
	default:
		return fmt.Errorf("unsupported scan type for MovementType: %T", src)
	}
	return nil
}

type NullMovementType struct {
	MovementType MovementType `json:"movement_type"`
	Valid        bool         `json:"valid"` // Valid is true if MovementType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMovementType) Scan(value interface{}) error {
	if value == nil {
		ns.MovementType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MovementType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMovementType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MovementType), nil
}

type UserRole string

const (
	UserRoleOWNER    UserRole = "OWNER"
	UserRoleMANAGER  UserRole = "MANAGER"
	UserRoleEMPLOYEE UserRole = "EMPLOYEE"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"user_role"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type Business struct {
	ID        uuid.UUID      `json:"id"`
	Name      string         `json:"name"`
	Category  string         `json:"category"`
	Country   sql.NullString `json:"country"`
	Currency  sql.NullString `json:"currency"`
	CreatedAt sql.NullTime   `json:"created_at"`
	UpdatedAt sql.NullTime   `json:"updated_at"`
}

type BusinessConfiguration struct {
	ID           uuid.UUID       `json:"id"`
	BusinessID   uuid.UUID       `json:"business_id"`
	ConfigSchema json.RawMessage `json:"config_schema"`
	Status       string          `json:"status"`
	CreatedAt    sql.NullTime    `json:"created_at"`
	UpdatedAt    sql.NullTime    `json:"updated_at"`
}

type BusinessMember struct {
	ID         uuid.UUID    `json:"id"`
	BusinessID uuid.UUID    `json:"business_id"`
	UserID     uuid.UUID    `json:"user_id"`
	Role       UserRole     `json:"role"`
	CreatedAt  sql.NullTime `json:"created_at"`
	UpdatedAt  sql.NullTime `json:"updated_at"`
}

type InventoryBalance struct {
	ProductID  uuid.UUID    `json:"product_id"`
	BusinessID uuid.UUID    `json:"business_id"`
	Quantity   string       `json:"quantity"`
	UpdatedAt  sql.NullTime `json:"updated_at"`
}

type InventoryMovement struct {
	ID             uuid.UUID      `json:"id"`
	BusinessID     uuid.UUID      `json:"business_id"`
	ProductID      uuid.UUID      `json:"product_id"`
	UserID         uuid.NullUUID  `json:"user_id"`
	Type           MovementType   `json:"type"`
	QuantityChange string         `json:"quantity_change"`
	BalanceAfter   string         `json:"balance_after"`
	ReferenceID    uuid.NullUUID  `json:"reference_id"`
	Notes          sql.NullString `json:"notes"`
	CreatedAt      sql.NullTime   `json:"created_at"`
}

type Product struct {
	ID                uuid.UUID             `json:"id"`
	BusinessID        uuid.UUID             `json:"business_id"`
	Sku               sql.NullString        `json:"sku"`
	Barcode           sql.NullString        `json:"barcode"`
	Name              string                `json:"name"`
	Description       sql.NullString        `json:"description"`
	SupplierID        uuid.NullUUID         `json:"supplier_id"`
	PurchasePrice     sql.NullString        `json:"purchase_price"`
	SellingPrice      sql.NullString        `json:"selling_price"`
	MinStockThreshold sql.NullString        `json:"min_stock_threshold"`
	DynamicFields     pqtype.NullRawMessage `json:"dynamic_fields"`
	CreatedAt         sql.NullTime          `json:"created_at"`
	UpdatedAt         sql.NullTime          `json:"updated_at"`
}

type Supplier struct {
	ID          uuid.UUID      `json:"id"`
	BusinessID  uuid.UUID      `json:"business_id"`
	Name        string         `json:"name"`
	ContactName sql.NullString `json:"contact_name"`
	Email       sql.NullString `json:"email"`
	Phone       sql.NullString `json:"phone"`
	CreatedAt   sql.NullTime   `json:"created_at"`
}

type User struct {
	ID          uuid.UUID      `json:"id"`
	FirebaseUid string         `json:"firebase_uid"`
	Email       string         `json:"email"`
	DisplayName sql.NullString `json:"display_name"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}
