// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const createBusiness = `-- name: CreateBusiness :one
INSERT INTO businesses (name, category, country, currency)
VALUES ($1, $2, $3, $4)
RETURNING id, name, category, country, currency, created_at, updated_at
`

type CreateBusinessParams struct {
	Name     string         `json:"name"`
	Category string         `json:"category"`
	Country  sql.NullString `json:"country"`
	Currency sql.NullString `json:"currency"`
}

func (q *Queries) CreateBusiness(ctx context.Context, arg CreateBusinessParams) (Business, error) {
	row := q.db.QueryRowContext(ctx, createBusiness,
		arg.Name,
		arg.Category,
		arg.Country,
		arg.Currency,
	)
	var i Business
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Category,
		&i.Country,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createBusinessMember = `-- name: CreateBusinessMember :one
INSERT INTO business_members (business_id, user_id, role)
VALUES ($1, $2, $3)
RETURNING id, business_id, user_id, role, created_at, updated_at
`

type CreateBusinessMemberParams struct {
	BusinessID uuid.UUID `json:"business_id"`
	UserID     uuid.UUID `json:"user_id"`
	Role       UserRole  `json:"role"`
}

func (q *Queries) CreateBusinessMember(ctx context.Context, arg CreateBusinessMemberParams) (BusinessMember, error) {
	row := q.db.QueryRowContext(ctx, createBusinessMember, arg.BusinessID, arg.UserID, arg.Role)
	var i BusinessMember
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (
    business_id, sku, barcode, name, description, supplier_id, 
    purchase_price, selling_price, min_stock_threshold, dynamic_fields
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
) RETURNING id, business_id, sku, barcode, name, description, supplier_id, purchase_price, selling_price, min_stock_threshold, dynamic_fields, created_at, updated_at
`

type CreateProductParams struct {
	BusinessID        uuid.UUID             `json:"business_id"`
	Sku               sql.NullString        `json:"sku"`
	Barcode           sql.NullString        `json:"barcode"`
	Name              string                `json:"name"`
	Description       sql.NullString        `json:"description"`
	SupplierID        uuid.NullUUID         `json:"supplier_id"`
	PurchasePrice     sql.NullString        `json:"purchase_price"`
	SellingPrice      sql.NullString        `json:"selling_price"`
	MinStockThreshold sql.NullString        `json:"min_stock_threshold"`
	DynamicFields     pqtype.NullRawMessage `json:"dynamic_fields"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, createProduct,
		arg.BusinessID,
		arg.Sku,
		arg.Barcode,
		arg.Name,
		arg.Description,
		arg.SupplierID,
		arg.PurchasePrice,
		arg.SellingPrice,
		arg.MinStockThreshold,
		arg.DynamicFields,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Sku,
		&i.Barcode,
		&i.Name,
		&i.Description,
		&i.SupplierID,
		&i.PurchasePrice,
		&i.SellingPrice,
		&i.MinStockThreshold,
		&i.DynamicFields,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSupplier = `-- name: CreateSupplier :one
INSERT INTO suppliers (business_id, name, contact_name, email, phone)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, business_id, name, contact_name, email, phone, created_at
`

type CreateSupplierParams struct {
	BusinessID  uuid.UUID      `json:"business_id"`
	Name        string         `json:"name"`
	ContactName sql.NullString `json:"contact_name"`
	Email       sql.NullString `json:"email"`
	Phone       sql.NullString `json:"phone"`
}

func (q *Queries) CreateSupplier(ctx context.Context, arg CreateSupplierParams) (Supplier, error) {
	row := q.db.QueryRowContext(ctx, createSupplier,
		arg.BusinessID,
		arg.Name,
		arg.ContactName,
		arg.Email,
		arg.Phone,
	)
	var i Supplier
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Name,
		&i.ContactName,
		&i.Email,
		&i.Phone,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (firebase_uid, email, display_name)
VALUES ($1, $2, $3)
RETURNING id, firebase_uid, email, display_name, created_at, updated_at
`

type CreateUserParams struct {
	FirebaseUid string         `json:"firebase_uid"`
	Email       string         `json:"email"`
	DisplayName sql.NullString `json:"display_name"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.FirebaseUid, arg.Email, arg.DisplayName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirebaseUid,
		&i.Email,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBusinessConfiguration = `-- name: GetBusinessConfiguration :one
SELECT id, business_id, config_schema, status, created_at, updated_at FROM business_configurations WHERE business_id = $1 LIMIT 1
`

func (q *Queries) GetBusinessConfiguration(ctx context.Context, businessID uuid.UUID) (BusinessConfiguration, error) {
	row := q.db.QueryRowContext(ctx, getBusinessConfiguration, businessID)
	var i BusinessConfiguration
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.ConfigSchema,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFirstBusiness = `-- name: GetFirstBusiness :one
SELECT id FROM businesses LIMIT 1
`

func (q *Queries) GetFirstBusiness(ctx context.Context) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, getFirstBusiness)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getInventoryBalance = `-- name: GetInventoryBalance :one
SELECT product_id, business_id, quantity, updated_at FROM inventory_balances WHERE product_id = $1 AND business_id = $2
`

type GetInventoryBalanceParams struct {
	ProductID  uuid.UUID `json:"product_id"`
	BusinessID uuid.UUID `json:"business_id"`
}

func (q *Queries) GetInventoryBalance(ctx context.Context, arg GetInventoryBalanceParams) (InventoryBalance, error) {
	row := q.db.QueryRowContext(ctx, getInventoryBalance, arg.ProductID, arg.BusinessID)
	var i InventoryBalance
	err := row.Scan(
		&i.ProductID,
		&i.BusinessID,
		&i.Quantity,
		&i.UpdatedAt,
	)
	return i, err
}

const getInventoryMovements = `-- name: GetInventoryMovements :many
SELECT id, business_id, product_id, user_id, type, quantity_change, balance_after, reference_id, notes, created_at FROM inventory_movements 
WHERE business_id = $1 AND ($2::uuid IS NULL OR product_id = $2::uuid)
ORDER BY created_at DESC
`

type GetInventoryMovementsParams struct {
	BusinessID uuid.UUID     `json:"business_id"`
	ProductID  uuid.NullUUID `json:"product_id"`
}

func (q *Queries) GetInventoryMovements(ctx context.Context, arg GetInventoryMovementsParams) ([]InventoryMovement, error) {
	rows, err := q.db.QueryContext(ctx, getInventoryMovements, arg.BusinessID, arg.ProductID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InventoryMovement
	for rows.Next() {
		var i InventoryMovement
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.ProductID,
			&i.UserID,
			&i.Type,
			&i.QuantityChange,
			&i.BalanceAfter,
			&i.ReferenceID,
			&i.Notes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProduct = `-- name: GetProduct :one
SELECT id, business_id, sku, barcode, name, description, supplier_id, purchase_price, selling_price, min_stock_threshold, dynamic_fields, created_at, updated_at FROM products WHERE id = $1 AND business_id = $2 LIMIT 1
`

type GetProductParams struct {
	ID         uuid.UUID `json:"id"`
	BusinessID uuid.UUID `json:"business_id"`
}

func (q *Queries) GetProduct(ctx context.Context, arg GetProductParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, getProduct, arg.ID, arg.BusinessID)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Sku,
		&i.Barcode,
		&i.Name,
		&i.Description,
		&i.SupplierID,
		&i.PurchasePrice,
		&i.SellingPrice,
		&i.MinStockThreshold,
		&i.DynamicFields,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProducts = `-- name: GetProducts :many
SELECT p.id, p.business_id, p.sku, p.barcode, p.name, p.description, p.supplier_id, p.purchase_price, p.selling_price, p.min_stock_threshold, p.dynamic_fields, p.created_at, p.updated_at, COALESCE(b.quantity, 0) as balance
FROM products p
LEFT JOIN inventory_balances b ON p.id = b.product_id
WHERE p.business_id = $1 
ORDER BY p.created_at DESC
`

type GetProductsRow struct {
	ID                uuid.UUID             `json:"id"`
	BusinessID        uuid.UUID             `json:"business_id"`
	Sku               sql.NullString        `json:"sku"`
	Barcode           sql.NullString        `json:"barcode"`
	Name              string                `json:"name"`
	Description       sql.NullString        `json:"description"`
	SupplierID        uuid.NullUUID         `json:"supplier_id"`
	PurchasePrice     sql.NullString        `json:"purchase_price"`
	SellingPrice      sql.NullString        `json:"selling_price"`
	MinStockThreshold sql.NullString        `json:"min_stock_threshold"`
	DynamicFields     pqtype.NullRawMessage `json:"dynamic_fields"`
	CreatedAt         sql.NullTime          `json:"created_at"`
	UpdatedAt         sql.NullTime          `json:"updated_at"`
	Balance           string                `json:"balance"`
}

func (q *Queries) GetProducts(ctx context.Context, businessID uuid.UUID) ([]GetProductsRow, error) {
	rows, err := q.db.QueryContext(ctx, getProducts, businessID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProductsRow
	for rows.Next() {
		var i GetProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.Sku,
			&i.Barcode,
			&i.Name,
			&i.Description,
			&i.SupplierID,
			&i.PurchasePrice,
			&i.SellingPrice,
			&i.MinStockThreshold,
			&i.DynamicFields,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Balance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSuppliers = `-- name: GetSuppliers :many
SELECT id, business_id, name, contact_name, email, phone, created_at FROM suppliers WHERE business_id = $1 ORDER BY name
`

func (q *Queries) GetSuppliers(ctx context.Context, businessID uuid.UUID) ([]Supplier, error) {
	rows, err := q.db.QueryContext(ctx, getSuppliers, businessID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Supplier
	for rows.Next() {
		var i Supplier
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.Name,
			&i.ContactName,
			&i.Email,
			&i.Phone,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserBusinessRole = `-- name: GetUserBusinessRole :one
SELECT m.business_id, m.role 
FROM business_members m
JOIN users u ON m.user_id = u.id
WHERE u.firebase_uid = $1
LIMIT 1
`

type GetUserBusinessRoleRow struct {
	BusinessID uuid.UUID `json:"business_id"`
	Role       UserRole  `json:"role"`
}

func (q *Queries) GetUserBusinessRole(ctx context.Context, firebaseUid string) (GetUserBusinessRoleRow, error) {
	row := q.db.QueryRowContext(ctx, getUserBusinessRole, firebaseUid)
	var i GetUserBusinessRoleRow
	err := row.Scan(&i.BusinessID, &i.Role)
	return i, err
}

const getUserByFirebaseUID = `-- name: GetUserByFirebaseUID :one
SELECT id, firebase_uid, email, display_name, created_at, updated_at FROM users WHERE firebase_uid = $1 LIMIT 1
`

func (q *Queries) GetUserByFirebaseUID(ctx context.Context, firebaseUid string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByFirebaseUID, firebaseUid)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirebaseUid,
		&i.Email,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const initializeInventoryBalance = `-- name: InitializeInventoryBalance :one
INSERT INTO inventory_balances (product_id, business_id, quantity)
VALUES ($1, $2, $3)
RETURNING product_id, business_id, quantity, updated_at
`

type InitializeInventoryBalanceParams struct {
	ProductID  uuid.UUID `json:"product_id"`
	BusinessID uuid.UUID `json:"business_id"`
	Quantity   string    `json:"quantity"`
}

func (q *Queries) InitializeInventoryBalance(ctx context.Context, arg InitializeInventoryBalanceParams) (InventoryBalance, error) {
	row := q.db.QueryRowContext(ctx, initializeInventoryBalance, arg.ProductID, arg.BusinessID, arg.Quantity)
	var i InventoryBalance
	err := row.Scan(
		&i.ProductID,
		&i.BusinessID,
		&i.Quantity,
		&i.UpdatedAt,
	)
	return i, err
}

const recordInventoryMovement = `-- name: RecordInventoryMovement :one
INSERT INTO inventory_movements (
    business_id, product_id, user_id, type, quantity_change, balance_after, notes
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, business_id, product_id, user_id, type, quantity_change, balance_after, reference_id, notes, created_at
`

type RecordInventoryMovementParams struct {
	BusinessID     uuid.UUID      `json:"business_id"`
	ProductID      uuid.UUID      `json:"product_id"`
	UserID         uuid.NullUUID  `json:"user_id"`
	Type           MovementType   `json:"type"`
	QuantityChange string         `json:"quantity_change"`
	BalanceAfter   string         `json:"balance_after"`
	Notes          sql.NullString `json:"notes"`
}

func (q *Queries) RecordInventoryMovement(ctx context.Context, arg RecordInventoryMovementParams) (InventoryMovement, error) {
	row := q.db.QueryRowContext(ctx, recordInventoryMovement,
		arg.BusinessID,
		arg.ProductID,
		arg.UserID,
		arg.Type,
		arg.QuantityChange,
		arg.BalanceAfter,
		arg.Notes,
	)
	var i InventoryMovement
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.ProductID,
		&i.UserID,
		&i.Type,
		&i.QuantityChange,
		&i.BalanceAfter,
		&i.ReferenceID,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const updateInventoryBalance = `-- name: UpdateInventoryBalance :one
UPDATE inventory_balances
SET quantity = quantity + $2, updated_at = CURRENT_TIMESTAMP
WHERE product_id = $1 AND business_id = $3
RETURNING product_id, business_id, quantity, updated_at
`

type UpdateInventoryBalanceParams struct {
	ProductID  uuid.UUID `json:"product_id"`
	Quantity   string    `json:"quantity"`
	BusinessID uuid.UUID `json:"business_id"`
}

func (q *Queries) UpdateInventoryBalance(ctx context.Context, arg UpdateInventoryBalanceParams) (InventoryBalance, error) {
	row := q.db.QueryRowContext(ctx, updateInventoryBalance, arg.ProductID, arg.Quantity, arg.BusinessID)
	var i InventoryBalance
	err := row.Scan(
		&i.ProductID,
		&i.BusinessID,
		&i.Quantity,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products
SET
    name = COALESCE($3, name),
    sku = COALESCE($4, sku),
    barcode = COALESCE($5, barcode),
    description = COALESCE($6, description),
    supplier_id = COALESCE($7, supplier_id),
    purchase_price = COALESCE($8, purchase_price),
    selling_price = COALESCE($9, selling_price)
WHERE id = $1 AND business_id = $2
RETURNING id, business_id, sku, barcode, name, description, supplier_id, purchase_price, selling_price, min_stock_threshold, dynamic_fields, created_at, updated_at
`

type UpdateProductParams struct {
	ID            uuid.UUID      `json:"id"`
	BusinessID    uuid.UUID      `json:"business_id"`
	Name          sql.NullString `json:"name"`
	Sku           sql.NullString `json:"sku"`
	Barcode       sql.NullString `json:"barcode"`
	Description   sql.NullString `json:"description"`
	SupplierID    uuid.NullUUID  `json:"supplier_id"`
	PurchasePrice sql.NullString `json:"purchase_price"`
	SellingPrice  sql.NullString `json:"selling_price"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, updateProduct,
		arg.ID,
		arg.BusinessID,
		arg.Name,
		arg.Sku,
		arg.Barcode,
		arg.Description,
		arg.SupplierID,
		arg.PurchasePrice,
		arg.SellingPrice,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Sku,
		&i.Barcode,
		&i.Name,
		&i.Description,
		&i.SupplierID,
		&i.PurchasePrice,
		&i.SellingPrice,
		&i.MinStockThreshold,
		&i.DynamicFields,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertBusinessConfiguration = `-- name: UpsertBusinessConfiguration :one
INSERT INTO business_configurations (business_id, config_schema, status)
VALUES ($1, $2, $3)
ON CONFLICT (business_id) DO UPDATE 
SET config_schema = EXCLUDED.config_schema, status = EXCLUDED.status, updated_at = CURRENT_TIMESTAMP
RETURNING id, business_id, config_schema, status, created_at, updated_at
`

type UpsertBusinessConfigurationParams struct {
	BusinessID   uuid.UUID       `json:"business_id"`
	ConfigSchema json.RawMessage `json:"config_schema"`
	Status       string          `json:"status"`
}

func (q *Queries) UpsertBusinessConfiguration(ctx context.Context, arg UpsertBusinessConfigurationParams) (BusinessConfiguration, error) {
	row := q.db.QueryRowContext(ctx, upsertBusinessConfiguration, arg.BusinessID, arg.ConfigSchema, arg.Status)
	var i BusinessConfiguration
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.ConfigSchema,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
