// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

type Business struct {
	ID            string                 `json:"id"`
	Name          string                 `json:"name"`
	Category      string                 `json:"category"`
	Country       *string                `json:"country,omitempty"`
	Currency      *string                `json:"currency,omitempty"`
	Configuration *BusinessConfiguration `json:"configuration,omitempty"`
}

type BusinessConfiguration struct {
	ID           string `json:"id"`
	ConfigSchema any    `json:"configSchema"`
	Status       string `json:"status"`
}

type CreateBusinessInput struct {
	Name     string  `json:"name"`
	Category string  `json:"category"`
	Country  *string `json:"country,omitempty"`
	Currency *string `json:"currency,omitempty"`
}

type CreateProductInput struct {
	Name              string   `json:"name"`
	Sku               *string  `json:"sku,omitempty"`
	Barcode           *string  `json:"barcode,omitempty"`
	Description       *string  `json:"description,omitempty"`
	SupplierID        *string  `json:"supplierId,omitempty"`
	PurchasePrice     *float64 `json:"purchasePrice,omitempty"`
	SellingPrice      *float64 `json:"sellingPrice,omitempty"`
	MinStockThreshold *float64 `json:"minStockThreshold,omitempty"`
	DynamicFields     any      `json:"dynamicFields,omitempty"`
	OpeningStock      *float64 `json:"openingStock,omitempty"`
}

type CreateSupplierInput struct {
	Name        string  `json:"name"`
	ContactName *string `json:"contactName,omitempty"`
	Email       *string `json:"email,omitempty"`
	Phone       *string `json:"phone,omitempty"`
}

type InventoryMovement struct {
	ID             string       `json:"id"`
	Product        *Product     `json:"product"`
	User           *User        `json:"user,omitempty"`
	Type           MovementType `json:"type"`
	QuantityChange float64      `json:"quantityChange"`
	BalanceAfter   float64      `json:"balanceAfter"`
	Notes          *string      `json:"notes,omitempty"`
	CreatedAt      time.Time    `json:"createdAt"`
}

type Mutation struct {
}

type Product struct {
	ID                string    `json:"id"`
	Sku               *string   `json:"sku,omitempty"`
	Barcode           *string   `json:"barcode,omitempty"`
	Name              string    `json:"name"`
	Description       *string   `json:"description,omitempty"`
	Supplier          *Supplier `json:"supplier,omitempty"`
	PurchasePrice     *float64  `json:"purchasePrice,omitempty"`
	SellingPrice      *float64  `json:"sellingPrice,omitempty"`
	MinStockThreshold *float64  `json:"minStockThreshold,omitempty"`
	DynamicFields     any       `json:"dynamicFields,omitempty"`
	Balance           float64   `json:"balance"`
}

type Query struct {
}

type Supplier struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	ContactName *string `json:"contactName,omitempty"`
	Email       *string `json:"email,omitempty"`
	Phone       *string `json:"phone,omitempty"`
}

type UpdateProductInput struct {
	ID            string   `json:"id"`
	Name          *string  `json:"name,omitempty"`
	Sku           *string  `json:"sku,omitempty"`
	Barcode       *string  `json:"barcode,omitempty"`
	Description   *string  `json:"description,omitempty"`
	SupplierID    *string  `json:"supplierId,omitempty"`
	PurchasePrice *float64 `json:"purchasePrice,omitempty"`
	SellingPrice  *float64 `json:"sellingPrice,omitempty"`
}

type User struct {
	ID          string  `json:"id"`
	FirebaseUID string  `json:"firebaseUid"`
	Email       string  `json:"email"`
	DisplayName *string `json:"displayName,omitempty"`
}

type MovementType string

const (
	MovementTypeOpeningStock MovementType = "OPENING_STOCK"
	MovementTypePurchase     MovementType = "PURCHASE"
	MovementTypeSale         MovementType = "SALE"
	MovementTypeReturn       MovementType = "RETURN"
	MovementTypeDamage       MovementType = "DAMAGE"
	MovementTypeLoss         MovementType = "LOSS"
	MovementTypeAdjustment   MovementType = "ADJUSTMENT"
	MovementTypeExpiry       MovementType = "EXPIRY"
)

var AllMovementType = []MovementType{
	MovementTypeOpeningStock,
	MovementTypePurchase,
	MovementTypeSale,
	MovementTypeReturn,
	MovementTypeDamage,
	MovementTypeLoss,
	MovementTypeAdjustment,
	MovementTypeExpiry,
}

func (e MovementType) IsValid() bool {
	switch e {
	case MovementTypeOpeningStock, MovementTypePurchase, MovementTypeSale, MovementTypeReturn, MovementTypeDamage, MovementTypeLoss, MovementTypeAdjustment, MovementTypeExpiry:
		return true
	}
	return false
}

func (e MovementType) String() string {
	return string(e)
}

func (e *MovementType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = MovementType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid MovementType", str)
	}
	return nil
}

func (e MovementType) MarshalGQL(w io.Writer) {
	_, _ = fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *MovementType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e MovementType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
