package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"
	"database/sql"
	"encoding/json"
	"fmt"
	"os"
	"strconv"
	"strings"

	"github.com/Aboyisnoone/inventory-saas-backend/db"
	"github.com/Aboyisnoone/inventory-saas-backend/graph/model"
	"github.com/Aboyisnoone/inventory-saas-backend/notifications"
	"github.com/google/generative-ai-go/genai"
	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
	"google.golang.org/api/option"
)

// RegisterUser is the resolver for the registerUser field.
func (r *mutationResolver) RegisterUser(ctx context.Context, firebaseUID string, email string, displayName *string) (*model.User, error) {
	dName := sql.NullString{}
	if displayName != nil {
		dName.String = *displayName
		dName.Valid = true
	}

	u, err := r.Queries.CreateUser(ctx, db.CreateUserParams{
		FirebaseUid: firebaseUID,
		Email:       email,
		DisplayName: dName,
	})
	if err != nil {
		return nil, err
	}

	return &model.User{
		ID:          u.ID.String(),
		FirebaseUID: u.FirebaseUid,
		Email:       u.Email,
		DisplayName: displayName,
	}, nil
}

// CreateBusiness is the resolver for the createBusiness field.
func (r *mutationResolver) CreateBusiness(ctx context.Context, input model.CreateBusinessInput) (*model.Business, error) {
	country := sql.NullString{}
	if input.Country != nil {
		country.String = *input.Country
		country.Valid = true
	}
	currency := sql.NullString{}
	if input.Currency != nil {
		currency.String = *input.Currency
		currency.Valid = true
	}

	b, err := r.Queries.CreateBusiness(ctx, db.CreateBusinessParams{
		Name:     input.Name,
		Category: input.Category,
		Country:  country,
		Currency: currency,
	})
	if err != nil {
		return nil, err
	}

	return &model.Business{
		ID:       b.ID.String(),
		Name:     b.Name,
		Category: b.Category,
		Country:  input.Country,
		Currency: input.Currency,
	}, nil
}

// GenerateAIConfiguration is the resolver for the generateAIConfiguration field.
func (r *mutationResolver) GenerateAIConfiguration(ctx context.Context, description string) (string, error) {
	apiKey := os.Getenv("GEMINI_API_KEY")
	if apiKey == "" {
		// Fallback mock if no API key is provided
		return `{"inventory_fields": ["SKU", "Barcode", "Product Name", "Purchase Price", "Selling Price", "Quantity", "Supplier", "Brand", "Warranty"], "requires_expiry_tracking": false, "requires_batch_tracking": false}`, nil
	}

	client, err := genai.NewClient(ctx, option.WithAPIKey(apiKey))
	if err != nil {
		return "", err
	}
	defer client.Close()

	model := client.GenerativeModel("gemini-3.8-flash")
	model.ResponseMIMEType = "application/json"

	prompt := "You are an expert inventory manager. Based on this business description, generate a JSON object with the following schema: { \"inventory_fields\": [\"field1\", \"field2\"], \"requires_expiry_tracking\": boolean, \"requires_batch_tracking\": boolean }. The inventory_fields should be a list of custom dynamic fields suitable for this business type (e.g. Size, Color for clothing; Batch Number, Expiry Date for pharmacy). Business: " + description

	resp, err := model.GenerateContent(ctx, genai.Text(prompt))
	if err != nil {
		return "", err
	}

	if len(resp.Candidates) > 0 && len(resp.Candidates[0].Content.Parts) > 0 {
		part := resp.Candidates[0].Content.Parts[0]
		if text, ok := part.(genai.Text); ok {
			return string(text), nil
		}
	}

	return "", fmt.Errorf("invalid response from Gemini")
}

// ApproveConfiguration is the resolver for the approveConfiguration field.
func (r *mutationResolver) ApproveConfiguration(ctx context.Context, configSchema any) (*model.BusinessConfiguration, error) {
	// Dummy Business ID for now until Auth context is fully injected
	bizID := getOrCreateBusiness(ctx, r.Queries)

	configBytes, _ := json.Marshal(configSchema)

	conf, err := r.Queries.UpsertBusinessConfiguration(ctx, db.UpsertBusinessConfigurationParams{
		BusinessID:   bizID,
		ConfigSchema: configBytes,
		Status:       "APPROVED",
	})
	if err != nil {
		return nil, err
	}

	var schema interface{}
	json.Unmarshal(conf.ConfigSchema, &schema)

	return &model.BusinessConfiguration{
		ID:           conf.ID.String(),
		ConfigSchema: schema,
		Status:       conf.Status,
	}, nil
}

// CreateSupplier is the resolver for the createSupplier field.
func (r *mutationResolver) CreateSupplier(ctx context.Context, input model.CreateSupplierInput) (*model.Supplier, error) {
	bizID := getOrCreateBusiness(ctx, r.Queries)

	cName := sql.NullString{}
	if input.ContactName != nil {
		cName.String = *input.ContactName
		cName.Valid = true
	}
	email := sql.NullString{}
	if input.Email != nil {
		email.String = *input.Email
		email.Valid = true
	}
	phone := sql.NullString{}
	if input.Phone != nil {
		phone.String = *input.Phone
		phone.Valid = true
	}

	s, err := r.Queries.CreateSupplier(ctx, db.CreateSupplierParams{
		BusinessID:  bizID,
		Name:        input.Name,
		ContactName: cName,
		Email:       email,
		Phone:       phone,
	})
	if err != nil {
		return nil, err
	}

	return &model.Supplier{
		ID:          s.ID.String(),
		Name:        s.Name,
		ContactName: input.ContactName,
		Email:       input.Email,
		Phone:       input.Phone,
	}, nil
}

// CreateProduct is the resolver for the createProduct field.
func (r *mutationResolver) CreateProduct(ctx context.Context, input model.CreateProductInput) (*model.Product, error) {
	bizID := getOrCreateBusiness(ctx, r.Queries)

	// Optional params conversion...
	sku, barcode, desc := sql.NullString{}, sql.NullString{}, sql.NullString{}
	if input.Sku != nil {
		sku.String = *input.Sku
		sku.Valid = true
	}
	if input.Barcode != nil {
		barcode.String = *input.Barcode
		barcode.Valid = true
	}
	if input.Description != nil {
		desc.String = *input.Description
		desc.Valid = true
	}

	pPrice, sPrice, minStock := sql.NullString{}, sql.NullString{}, sql.NullString{}
	if input.PurchasePrice != nil {
		pPrice.String = floatToDecimalStr(*input.PurchasePrice)
		pPrice.Valid = true
	}
	if input.SellingPrice != nil {
		sPrice.String = floatToDecimalStr(*input.SellingPrice)
		sPrice.Valid = true
	}
	if input.MinStockThreshold != nil {
		minStock.String = floatToDecimalStr(*input.MinStockThreshold)
		minStock.Valid = true
	}

	var suppID uuid.NullUUID
	if input.SupplierID != nil {
		id, _ := uuid.Parse(*input.SupplierID)
		suppID.UUID = id
		suppID.Valid = true
	}

	var dFields pqtype.NullRawMessage
	if input.DynamicFields != nil {
		b, _ := json.Marshal(input.DynamicFields)
		dFields.RawMessage = b
		dFields.Valid = true
	}

	p, err := r.Queries.CreateProduct(ctx, db.CreateProductParams{
		BusinessID:        bizID,
		Sku:               sku,
		Barcode:           barcode,
		Name:              input.Name,
		Description:       desc,
		SupplierID:        suppID,
		PurchasePrice:     pPrice,
		SellingPrice:      sPrice,
		MinStockThreshold: minStock,
		DynamicFields:     dFields,
	})
	if err != nil {
		return nil, err
	}

	// Create initial balance
	if input.OpeningStock != nil && *input.OpeningStock > 0 {
		_, _ = r.Queries.InitializeInventoryBalance(ctx, db.InitializeInventoryBalanceParams{
			ProductID:  p.ID,
			BusinessID: bizID,
			Quantity:   floatToDecimalStr(*input.OpeningStock),
		})

		_, _ = r.Queries.RecordInventoryMovement(ctx, db.RecordInventoryMovementParams{
			BusinessID:     bizID,
			ProductID:      p.ID,
			UserID:         getUserID(ctx),
			Type:           db.MovementTypeOPENINGSTOCK,
			QuantityChange: floatToDecimalStr(*input.OpeningStock),
			BalanceAfter:   floatToDecimalStr(*input.OpeningStock),
		})
	} else {
		_, _ = r.Queries.InitializeInventoryBalance(ctx, db.InitializeInventoryBalanceParams{
			ProductID:  p.ID,
			BusinessID: bizID,
			Quantity:   "0",
		})
	}

	return &model.Product{
		ID:   p.ID.String(),
		Name: p.Name,
	}, nil
}

// UpdateProduct is the resolver for the updateProduct field.
func (r *mutationResolver) UpdateProduct(ctx context.Context, input model.UpdateProductInput) (*model.Product, error) {
	bizID := getOrCreateBusiness(ctx, r.Queries)

	pID, err := uuid.Parse(input.ID)
	if err != nil {
		return nil, err
	}

	name, sku, barcode, desc := sql.NullString{}, sql.NullString{}, sql.NullString{}, sql.NullString{}
	if input.Name != nil {
		name.String = *input.Name
		name.Valid = true
	}
	if input.Sku != nil {
		sku.String = *input.Sku
		sku.Valid = true
	}
	if input.Barcode != nil {
		barcode.String = *input.Barcode
		barcode.Valid = true
	}
	if input.Description != nil {
		desc.String = *input.Description
		desc.Valid = true
	}

	pPrice, sPrice := sql.NullString{}, sql.NullString{}
	if input.PurchasePrice != nil {
		pPrice.String = floatToDecimalStr(*input.PurchasePrice)
		pPrice.Valid = true
	}
	if input.SellingPrice != nil {
		sPrice.String = floatToDecimalStr(*input.SellingPrice)
		sPrice.Valid = true
	}

	var suppID uuid.NullUUID
	if input.SupplierID != nil {
		sid, err := uuid.Parse(*input.SupplierID)
		if err == nil {
			suppID = uuid.NullUUID{UUID: sid, Valid: true}
		}
	}

	p, err := r.Queries.UpdateProduct(ctx, db.UpdateProductParams{
		ID:            pID,
		Name:          name,
		Sku:           sku,
		Barcode:       barcode,
		Description:   desc,
		SupplierID:    suppID,
		PurchasePrice: pPrice,
		SellingPrice:  sPrice,
		BusinessID:    bizID,
	})
	if err != nil {
		return nil, err
	}

	// Re-fetch balance
	var balance float64 = 0
	bal, err := r.Queries.GetInventoryBalance(ctx, db.GetInventoryBalanceParams{
		ProductID:  p.ID,
		BusinessID: bizID,
	})
	if err == nil {
		balance = parseDecimalStr(bal.Quantity)
	}

	var sPriceRet *float64
	if p.SellingPrice.Valid {
		sp := parseDecimalStr(p.SellingPrice.String)
		sPriceRet = &sp
	}

	var skuRet *string
	if p.Sku.Valid {
		skuRet = &p.Sku.String
	}
	var barcodeRet *string
	if p.Barcode.Valid {
		barcodeRet = &p.Barcode.String
	}

	return &model.Product{
		ID:           p.ID.String(),
		Name:         p.Name,
		Sku:          skuRet,
		Barcode:      barcodeRet,
		Balance:      balance,
		SellingPrice: sPriceRet,
	}, nil
}

// RecordMovement is the resolver for the recordMovement field.
func (r *mutationResolver) RecordMovement(ctx context.Context, productID string, typeArg model.MovementType, quantityChange float64, notes *string) (*model.InventoryMovement, error) {
	bizID := getOrCreateBusiness(ctx, r.Queries)
	pID, err := uuid.Parse(productID)
	if err != nil {
		return nil, err
	}

	// 1. Update the balance
	bal, err := r.Queries.UpdateInventoryBalance(ctx, db.UpdateInventoryBalanceParams{
		ProductID:  pID,
		Quantity:   floatToDecimalStr(quantityChange),
		BusinessID: bizID,
	})
	if err != nil {
		return nil, err
	}

	// 2. Record the movement
	n := sql.NullString{}
	if notes != nil {
		n.String = *notes
		n.Valid = true
	}
	m, err := r.Queries.RecordInventoryMovement(ctx, db.RecordInventoryMovementParams{
		BusinessID:     bizID,
		ProductID:      pID,
		UserID:         getUserID(ctx),
		Type:           db.MovementType(typeArg),
		QuantityChange: floatToDecimalStr(quantityChange),
		BalanceAfter:   bal.Quantity,
		Notes:          n,
	})
	if err != nil {
		return nil, err
	}

	// 3. Telegram Alert Check
	// Convert balance to float to check threshold
	balanceFloat, _ := strconv.ParseFloat(bal.Quantity, 64)
	if balanceFloat < 10 { // Hardcoded threshold for demo
		// Get product name
		if p, err := r.Queries.GetProduct(ctx, db.GetProductParams{ID: pID, BusinessID: bizID}); err == nil {
			// Get Telegram config
			if config, err := r.Queries.GetBusinessConfiguration(ctx, bizID); err == nil {
				var confMap map[string]interface{}
				if json.Unmarshal(config.ConfigSchema, &confMap) == nil {
					if token, ok := confMap["telegram_bot_token"].(string); ok && token != "" {
						if chatID, ok := confMap["telegram_chat_id"].(string); ok && chatID != "" {
							msg := fmt.Sprintf("🚨 *Low Stock Alert*\n\nProduct: %s\nCurrent Balance: %s units\n\nPlease restock soon!", p.Name, bal.Quantity)
							go notifications.SendTelegramAlert(token, chatID, msg)
						}
					}
				}
			}
		}
	}

	var resNotes *string
	if m.Notes.Valid {
		resNotes = &m.Notes.String
	}
	return &model.InventoryMovement{
		ID:             m.ID.String(),
		Type:           model.MovementType(m.Type),
		QuantityChange: parseDecimalStr(m.QuantityChange),
		BalanceAfter:   parseDecimalStr(m.BalanceAfter),
		Notes:          resNotes,
		CreatedAt:      m.CreatedAt.Time,
	}, nil
}

// AskInventoryAssistant is the resolver for the askInventoryAssistant field.
func (r *mutationResolver) AskInventoryAssistant(ctx context.Context, message string) (string, error) {
	apiKey := os.Getenv("GEMINI_API_KEY")
	if apiKey == "" {
		return "I am unable to answer right now (API Key not configured).", nil
	}

	bizID := getOrCreateBusiness(ctx, r.Queries)
	dbProducts, err := r.Queries.GetProducts(ctx, bizID)

	// Create context string
	var productsContext strings.Builder
	productsContext.WriteString("Current Inventory:\n")
	if err == nil {
		for _, p := range dbProducts {
			productsContext.WriteString(fmt.Sprintf("- %s (SKU: %s): %s in stock (Price: $%s)\n",
				p.Name, p.Sku.String, p.Balance, p.SellingPrice))
		}
	} else {
		productsContext.WriteString("Failed to load inventory.\n")
	}

	client, err := genai.NewClient(ctx, option.WithAPIKey(apiKey))
	if err != nil {
		return "", err
	}
	defer client.Close()

	model := client.GenerativeModel("gemini-3.8-flash")
	model.SystemInstruction = &genai.Content{
		Parts: []genai.Part{
			genai.Text("You are an expert inventory manager assistant. You answer questions strictly about the user's inventory based on the provided context. If a user asks a question completely unrelated to business, inventory, or management, decline gracefully.\n\n" + productsContext.String()),
		},
	}

	resp, err := model.GenerateContent(ctx, genai.Text(message))
	if err != nil {
		return "", err
	}

	if len(resp.Candidates) > 0 && len(resp.Candidates[0].Content.Parts) > 0 {
		if textPart, ok := resp.Candidates[0].Content.Parts[0].(genai.Text); ok {
			return string(textPart), nil
		}
	}

	return "I could not generate a response.", nil
}

// UpdateTelegramConfig is the resolver for the updateTelegramConfig field.
func (r *mutationResolver) UpdateTelegramConfig(ctx context.Context, botToken string, chatID string) (bool, error) {
	bizID := getOrCreateBusiness(ctx, r.Queries)

	// Create JSON payload
	configPayload := map[string]interface{}{
		"telegram_bot_token": botToken,
		"telegram_chat_id":   chatID,
	}
	jsonBytes, err := json.Marshal(configPayload)
	if err != nil {
		return false, err
	}

	_, err = r.Queries.UpsertBusinessConfiguration(ctx, db.UpsertBusinessConfigurationParams{
		BusinessID:   bizID,
		ConfigSchema: jsonBytes,
		Status:       "ACTIVE",
	})
	if err != nil {
		return false, err
	}

	return true, nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	return &model.User{ID: "1", Email: "test@example.com"}, nil
}

// MyBusiness is the resolver for the myBusiness field.
func (r *queryResolver) MyBusiness(ctx context.Context) (*model.Business, error) {
	return &model.Business{ID: "1", Name: "Mock Business"}, nil
}

// Products is the resolver for the products field.
func (r *queryResolver) Products(ctx context.Context) ([]*model.Product, error) {
	bizID := getOrCreateBusiness(ctx, r.Queries)
	dbProducts, err := r.Queries.GetProducts(ctx, bizID)
	if err != nil {
		return nil, err
	}

	var products []*model.Product
	for _, p := range dbProducts {
		sellingPrice := parseDecimalStr(p.SellingPrice.String)
		products = append(products, &model.Product{
			ID:           p.ID.String(),
			Name:         p.Name,
			Sku:          &p.Sku.String,
			Balance:      parseDecimalStr(p.Balance),
			SellingPrice: &sellingPrice,
		})
	}
	return products, nil
}

// Suppliers is the resolver for the suppliers field.
func (r *queryResolver) Suppliers(ctx context.Context) ([]*model.Supplier, error) {
	bizID := getOrCreateBusiness(ctx, r.Queries)
	dbSuppliers, err := r.Queries.GetSuppliers(ctx, bizID)
	if err != nil {
		return nil, err
	}

	var suppliers []*model.Supplier
	for _, s := range dbSuppliers {
		suppliers = append(suppliers, &model.Supplier{
			ID:          s.ID.String(),
			Name:        s.Name,
			ContactName: &s.ContactName.String,
			Email:       &s.Email.String,
			Phone:       &s.Phone.String,
		})
	}
	return suppliers, nil
}

// InventoryHistory is the resolver for the inventoryHistory field.
func (r *queryResolver) InventoryHistory(ctx context.Context, productID *string) ([]*model.InventoryMovement, error) {
	bizID := getOrCreateBusiness(ctx, r.Queries)

	var pID uuid.NullUUID
	if productID != nil {
		id, err := uuid.Parse(*productID)
		if err == nil {
			pID.UUID = id
			pID.Valid = true
		}
	}

	movements, err := r.Queries.GetInventoryMovements(ctx, db.GetInventoryMovementsParams{
		BusinessID: bizID,
		ProductID:  pID,
	})
	if err != nil {
		return nil, err
	}

	var res []*model.InventoryMovement
	for _, m := range movements {
		var notes *string
		if m.Notes.Valid {
			notes = &m.Notes.String
		}
		res = append(res, &model.InventoryMovement{
			ID:             m.ID.String(),
			Type:           model.MovementType(m.Type),
			QuantityChange: parseDecimalStr(m.QuantityChange),
			BalanceAfter:   parseDecimalStr(m.BalanceAfter),
			Notes:          notes,
			CreatedAt:      m.CreatedAt.Time,
		})
	}
	return res, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type (
	mutationResolver struct{ *Resolver }
	queryResolver    struct{ *Resolver }
)
